config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/user' => "fmeas#index", :as => :user_root
  root to: 'pages#home'
  get '/playground', to: 'pages#playground'
  get '/blog', to: 'pages#blog'
  get '/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :fmeas, only: %i[index edit create update destroy] do
    member do
      get 'collaboration'
      get 'download'
    end
    # collection do
    #   get 'download'
    # end
  end
  resources :functions, only: %i[update create destroy]
  resources :failure_modes, only: %i[update create destroy]
  resources :effects, only: %i[update create destroy]
  resources :causes, only: %i[update create destroy]
end

app/models/fmea.rb
class Fmea < ApplicationRecord
  belongs_to :risk_matrix
  has_many :activities
  has_many :functions, dependent: :destroy
  has_many :failure_modes, through: :functions
  has_many :effects, through: :failure_modes
  has_many :causes, through: :failure_modes
  has_many :actions, through: :causes

  # Fmea  will have many attached images
  has_many_attached :images

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :fmea_type, inclusion: { in: %w(Design System Process), message: "%{value} is not 'Design', 'System' or 'Process'" }
end

app/controllers/fmeas_controller.rb
class FmeasController < ApplicationController
  include FmeaHelper
  before_action :set_fmea, only: [:edit, :update, :collaboration, :destroy, :download]

  def index
    @query = params[:search][:query] if params[:search].present?

    if @query.present?
      sql_query = " \
      fmeas.title ILIKE :query \
      OR risk_matrices.name ILIKE :query \
      "
      @fmeas = Fmea.joins(:risk_matrix).where(sql_query, query: "%#{@query}%")
      # @fmeas = Fmea.where("title ILIKE ?", "%#{@query}%")
    else
      @fmeas = Fmea.all
    end

    @fmea = Fmea.new
  end

  def edit
  end

  def create
    @fmea = Fmea.new(fmea_params)
    @fmea.fmea_type = "Design"
    if @fmea.save
      redirect_to(edit_fmea_path(@fmea))
    else
      @fmeas = Fmea.all
      render action: :index
    end
  end

  def update
    @fmea.update(fmea_params)
    redirect_to edit_fmea_path(@fmea)
  end

  def destroy
    @fmea.destroy
    redirect_to(fmeas_path)
  end

  def collaboration
    # check if fmea contains any failure modes

    if @fmea.failure_modes.present?

      # assign @query if query is provided
      @query = params[:failure_mode_id] if params[:failure_mode_id].present?

      # Check if the failure_mode exists
      if FailureMode.exists?(@query.to_i)
        # if yes: assign to failure_mode
        failure_mode = FailureMode.find(@query.to_i)
        # now check if failure_mode belongs to fmea
        if @fmea == failure_mode.function.fmea
          # if yes: assign show_instances so view renders in correct location
          @show_failure_mode = failure_mode
          @show_function = @show_failure_mode.function
        else
          # else: render the first function and failure mode
          @show_failure_mode = find_first_failure_mode(@fmea)
          @show_function = @show_failure_mode.function
        end
      else
        # render the first function and failure mode
        @show_failure_mode = find_first_failure_mode(@fmea)
        @show_function = @show_failure_mode.function
      end

    else
      flash[:alert] = "You must have at least 1 failure mode to use the collaboration mode"
      render :edit
    end
  end

  def download
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=FMEA-#{@fmea.title}.xlsx"
      }
      format.html { render :index }
    end
  end

  private

  def set_fmea
    @fmea = Fmea.find(params[:id])
  end

  def fmea_params
    params.require(:fmea).permit(:title, :risk_matrix_id, :description, images: [])
  end

end

app/helpers/fmea_helper.rb
module FmeaHelper
  def fmea_type_icon(fmea)
    #'Design', 'System' or 'Process'
    if fmea.fmea_type == "Process"
      ('<i class="fas fa-tasks"></i>').html_safe
    elsif fmea.fmea_type == "System"
      ('<i class="fas fa-project-diagram"></i>').html_safe
    else
      ('<i class="fas fa-drafting-compass"></i>').html_safe
    end
  end

  def product_images?(fmea)
    fmea.images.length == 0 ? false : true
  end

  def find_first_failure_mode(fmea)
    fmea.functions.each do |function|
      if function.failure_modes.present?
        return function.failure_modes[0]
      end
    end
  end
end

app/views/fmeas/edit_fmea/_add_card_modal.html.erb
<div class="modal fade" id=<%= "add#{element.class.name}"%>>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h3 class="modal-title">Add a <%= element.class.name %></h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <%= simple_form_for(element, remote: true) do |f| %>
          <%= f.input :description, as: :text, :input_html => { placeholder: placeholder_text(element) } %>

          <%# hidden form field to communicate to controller what the parent fmea/function/failure_mode/cause is %>
          <%# edit_fmea js controller will overwrite the value for the function/failure_mode/cause %>
          <%= f.input "#{element.parent.model_name.param_key}_id", as: :hidden, :input_html => { value: element.parent.id, :data => {:target => "edit-fmea.#{element.class.to_s.downcase}Form"} } %>

          <div class="btn btn-success">
            <%= f.button :submit, class: "btn-clean", data: {dismiss: :dismiss} %>
          </div>
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/fmeas/edit_fmea/_add_cards.html.erb
<!-- Created 4 times, once per card type. The parent id value will be overwritten using the js controller -->
<%= render "fmeas/edit_fmea/add_card_modal", element: Function.new(fmea: fmea) %>
<%= render "fmeas/edit_fmea/add_card_modal", element: FailureMode.new(function: Function.new(fmea: fmea)) %>
<%= render "fmeas/edit_fmea/add_card_modal", element: Cause.new(failure_mode: FailureMode.new(function: Function.new(fmea: fmea))) %>
<%= render "fmeas/edit_fmea/add_card_modal", element: Effect.new(failure_mode: FailureMode.new(function: Function.new(fmea: fmea))) %>


<div class="all-add-cards-buttons pt-4" data-target="edit-fmea.actionMenu">
  <div class="add-card-button" id="add-function-button">
    <a  data-toggle="modal" data-target="#addFunction" href="#"><%= image_tag("actions/add_function.svg") %></a>
    <p>add function</p>
  </div>
  <div class="add-card-button hidden-button" id="add-failure-mode-button" >
    <a data-toggle="modal" data-target="#addFailureMode" data-action="click->edit-fmea#createFailureMode" href="#"><%= image_tag("actions/add_failure_mode.svg") %></a>
    <p>add failure mode</p>
  </div>
  <div class="add-card-button hidden-button" id="add-cause-button" >
    <a data-toggle="modal" data-target="#addCause" data-action="click->edit-fmea#createCause" href="#"><%= image_tag("actions/add_cause.svg") %></a>
    <p>add cause</p>
  </div>
  <div class="add-card-button hidden-button" id="add-effect-button" >
    <a data-toggle="modal" data-target="#addEffect" data-action="click->edit-fmea#createEffect" href="#"><%= image_tag("actions/add_effect.svg") %></a>
    <p>add effect</p>
  </div>
  <div class="add-card-button hidden-button" id="delete-button" >
    <a data-action="click->edit-fmea#delete" data-method="delete" data-target="edit-fmea.delete" rel="nofollow" data-confirm="Are you sure you want to delete the selected item?" href="/type/id"><%= image_tag("actions/delete_v2.svg") %></a>
    <p>delete <span data-target="edit-fmea.delete"></span></p>
  </div>
  <div class="add-card-button hidden-button" id="clear-selection-button">
    <span data-action="click->edit-fmea#select" data-card-type="" data-id="" href=""><%= image_tag("actions/clear_selection_v2.svg") %></span>
    <p>clear selection <span data-target="edit-fmea.delete"></span></p>
  </div>
</div>

app/views/fmeas/edit_fmea/_card_content.html.erb
<!-- Element Logic -->
<% element_class = element.class.to_s.downcase %>
<% element_icon_path = element.class.to_s.downcase %>

<!-- Card HTML -->
<div class="card-background" data-target="edit-fmea.card collaboration.<%= element.model_name.param_key%>" data-action="click->edit-fmea#select" data-card-type="<%= element.class.name.downcase  %>" data-id="<%= element.id %>"  data-parent-id="<%= element.parent.id %>" id="<%= card_id(element) %>" data-controller="clipboard" >
<!--   <div class="card-icon-box <%= element_class %>"> -->
    <%= image_tag( "icons/#{element_icon_path}_v2.svg", class: "card-icon") %>
<!--   </div> -->
  <div class="element-text" data-target="clipboard.source">
    <%= element.description %>
  </div>
  <!-- If card is cause or effect show sev/occ rating -->

  <div class="<%= "so-rating #{rating_color(element)}" if show_rating(element) %>">
    <%= rating(element) %>
    <!-- Tooltip -->
    <%= render "fmeas/edit_fmea/sev_occ_tooltip", element: element %>
  </div>
  <!-- /rating -->
  <div class="edit-card">
      <a data-toggle="modal" data-target=<%="#edit#{element.class.to_s}#{element.id}Description"%> href="#"><i class="fas fa-pen"></i></a>
      <span data-target="clipboard.copybutton" data-action="click->clipboard#copy" class="clip-hover copy-button-hide"><i class="fas fa-clipboard"></i></span>
  </div>
</div>

<!-- Edit Modal -->
<%= render "fmeas/edit_fmea/edit_description_modal", element: element %>

app/views/fmeas/edit_fmea/_card_structure.html.erb
<!-- When you render this component, pass it the object as an element (element: object) -->

<div class="card-structure-main">
  <div class="card-structure-top"></div>
  <div class="card-structure-bottom">
    <div class="card-structure-bottom-left">
      <div class="left-top"></div>
      <div class="left-bottom"></div>
    </div>
    <div class="card-structure-bottom-right" >
      <%= render "fmeas/edit_fmea/card_content", element: element %>
    </div>
  </div>
</div>

app/views/fmeas/edit_fmea/_edit_description_modal.html.erb
<!-- Need to tag modal with object id to ensure we have a unqiue target-->
<div class="modal fade" id=<%="edit#{element.class.to_s}#{element.id}Description"%>>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h3 class="modal-title">Edit <%= element.class.to_s %> Description</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">

        <%= simple_form_for(element, remote: true) do |f| %>

          <%= f.input :description, as: :text %>

          <% if element.class.to_s.downcase == "effect" %>
            <%= f.input :severity, {collection: (1..rating_scale(element)).to_a} %>
          <% end %>
          <% if element.class.to_s.downcase == "cause" %>
            <%= f.input :occurrence, {collection: (1..rating_scale(element)).to_a} %>
          <% end %>

          <div class="btn btn-success">
            <%= f.button :submit, class: "btn-clean", data: {dismiss: :dismiss} %>
          </div>

          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/fmeas/edit_fmea/_edit_fmea_modal.html.erb
<div class="modal fade" id="editFmeaDetails">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h3 class="modal-title">Edit FMEA</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <%= simple_form_for fmea do |f| %>
          <%= f.input :title, as: :string %>
          <%= f.input :description, as: :text %>
          <%= f.input :images, as: :file, input_html: { multiple: true } %>
          <div class="float-right"></div>
          <div class="btn btn-success">
            <%= f.button :submit, class: "btn-clean", data: {dismiss: :dismiss} %>
          </div>
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/fmeas/edit_fmea/_failure_modes_structure.html.erb
<div class="one-failure-mode">
  <div class="one-failure-mode-left">
  <div class="fm-left"></div>
  <div class="fm-right">
    <div class="fm-element">
      <%= render "fmeas/edit_fmea/card_structure", element: failure_mode %>
    </div>
    <div class="causes-structure">
      <div class="cause-left"></div>
      <div class="cause-right">
        <% causes = failure_mode.causes %>
        <% causes = order_and_select(causes) %>
        <% causes.each do |cause| %>
          <div class="one-cause">
            <%= render "fmeas/edit_fmea/card_structure", element: cause %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="cause-right-bottom"></div>
  </div>
  </div>

  <% counter = 0 %>
  <% effects = failure_mode.effects %>
  <% effects = order_and_select(effects) %>

  <% unless effects.length == 0 %>
    <div class="one-failure-mode-right">
      <div class="effects-top"></div>
      <div class="effects-bottom">
        <div class="effects-bottom-left">
          <div class="effects-bottom-left-top"></div>
          <div class="effects-bottom-left-bottom"></div>
        </div>
        <div class="effects-bottom-right">
          <% effects.each do |effect| %>
            <% counter += 1 %>
            <% if counter > 1 %>
              <div style="height: 10px;"></div>
            <% end %>
              <div class="card-structure-bottom-right">
                <%= render "fmeas/edit_fmea/card_content", element: effect  %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/fmeas/edit_fmea/_fmea_header.html.erb
<div class="fmea-header" data-controller="product-header" data-action="scroll@window->product-header#scroll" data-target="product-header.header">
  <div class="fmea-product-image" data-target="product-header.productImage">
    <% if product_images?(fmea) %>
      <%= render "fmeas/edit_fmea/product_image_carousel", fmea: fmea %>
    <% else %>
      <i class="fas fa-file-upload"></i>
    <% end  %>
  </div>
  <div class="fmea-details">
    <div class="fmea-details-edit">
      <a data-toggle="modal" data-target="#editFmeaDetails" href="#"><i class="fas fa-pen"></i></a>
    </div>
    <h2><span class="light-blue"><%= fmea_type_icon(fmea) %></span> <%= fmea.title %></h2>
    <p><small><span class="light-blue"><i class="fas fa-th"></i></span>  <%= fmea.risk_matrix.name %></small></p>
    <p><%= simple_format(fmea.description) %></p>
  </div>
  <div data-target="product-header.headerRight" class="fmea-header-right ">
    <div class="header-stats">
      <div class="fmea-stat">
        <%= image_tag("statistic_icons/function.svg", class: "pr-1") %>
        <span class="stat-number"><%= fmea.functions.count %></span>
      </div>
      <div class="fmea-stat">
        <%= image_tag("statistic_icons/failure_mode.svg", class: "pr-1") %>
        <%= fmea.failure_modes.count %>
      </div>
      <div class="fmea-stat">
        <%= image_tag("statistic_icons/cause.svg", class: "pr-1") %>
        <%= fmea.causes.count %>
      </div>
      <div class="fmea-stat">
        <%= image_tag("statistic_icons/effect.svg", class: "pr-1") %>
        <%= fmea.effects.count %>
      </div>
    </div>
    <div class="header-collaboration-mode ">
      <%= link_to(collaboration_fmea_path(fmea), class: "btn btn-ghost btn-collaboration") do %>
        <i class="fas fa-users"></i> <span class="hide-small">Collaboration</span>
      <% end %>
      <%= link_to(download_fmea_path(fmea, format: :xlsx), data: {turbolinks: false}, class: "btn btn-ghost btn-collaboration") do %>
        <i class="fas fa-cloud-download-alt"></i> <span class="hide-small">Download</span>
      <% end %>
    </div>
  </div>
</div>

<!-- The Edit FMEA Modal -->
<%= render "fmeas/edit_fmea/edit_fmea_modal", fmea: fmea %>

<!-- Render Image Zoom Modal if product has images -->
<% if product_images?(fmea) %>
  <% fmea.images.each_with_index do |image, img_num| %>
    <%= render "fmeas/edit_fmea/image_modal", fmea: fmea, img_num: img_num %>
  <% end %>
<% end  %>

app/views/fmeas/edit_fmea/_image_modal.html.erb
<!-- Image Modal must contain image id -->
<div class="modal fade" id="imageModal<%= img_num %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <!--Content-->
    <div class="modal-content">
      <!--Body-->
      <div class="modal-body mb-0 p-0">
        <img style="border-radius: 10px 10px 0 0; width: 100%" src="<%= cl_image_path(fmea.images[img_num].key) %>">
      </div>
      <!--Footer-->
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
    <!--/.Content-->
  </div>
</div>

app/views/fmeas/edit_fmea/_product_image_carousel.html.erb
<div id="carouselFMEA" class="carousel slide" data-ride="carousel" data-interval="false">
  <!-- Carousel Indicators -->
  <ol class="carousel-indicators">
    <% fmea.images.each_with_index do |image, i| %>
      <% css_class = i == 0 ? "active" : ""  %>
      <li data-target="#carouselFMEA" data-slide-to="<%= i %>" class="<%= css_class %>"></li>
    <% end %>
  </ol>
  <!-- Carousel Images -->
  <div class="carousel-inner">
    <% fmea.images.each_with_index do |image, i| %>
      <% css_class = i == 0 ? "carousel-item active" : "carousel-item"  %>
      <div class="<%= css_class %>">
        <%# data-toggle and data-target attr are used to target the correct model %>
        <img class="d-block w-100" data-toggle="modal" data-target="#imageModal<%= i %>" src="<%= cl_image_path(image.key, width: 300, height: 300, crop: :fill) %>">
      </div>
    <% end %>
  </div>
  <!-- Bootstrap controls -->
  <a class="carousel-control-prev" href="#carouselFMEA" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselFMEA" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/fmeas/edit_fmea/_sev_occ_tooltip.html.erb
<div class="tool-tip">
  <%= tooltip_text(element) %>
  <div class="arrow-down"></div>
</div>