config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/user' => "fmeas#index", :as => :user_root
  root to: 'pages#home'
  get '/playground', to: 'pages#playground'
  get '/blog', to: 'pages#blog'
  get '/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :fmeas, only: %i[index edit create update destroy] do
    member do
      get 'collaboration'
      get 'download'
    end
    # collection do
    #   get 'download'
    # end
  end
  resources :functions, only: %i[update create destroy]
  resources :failure_modes, only: %i[update create destroy]
  resources :effects, only: %i[update create destroy]
  resources :causes, only: %i[update create destroy]
end

app/views/shared/_copy_alerts.html.erb
<div class="alert alert-success hidden" role="alert" id="copyalert">
</div>

app/views/shared/_dashboard_list.html.erb
<% fmeas = elements %>

<!-- To start with, we have the little title bar on top with all the descriptions -->
<div class="container">
  <div class="row">
    <div class="col-1">
        <div></div> <!-- This is where the avatar would go for all the FMEAs. -->
    </div>
    <div class="col-2">
      <h6 class="text-secondary">Title</h6>
    </div>
    <div class="col-2">
      <h6 class="text-secondary">Risk Matrix</h6>
    </div>
    <div class="col-2">
      <h6 class="text-secondary">Last Updated Date</h6>
    </div>
    <div class="col-3">
      <h6 class="text-secondary">Summary</h6>
    </div>
    <div class="col-2">
      <h6 class="text-secondary">Actions</h6>
    </div>
  </div>

  <!-- Now, we insert all the individual fmeas -->
  <br>

  <% fmeas.each do |fmea| %>
    <div class="my-auto dashboard-list-item">
      <%= render "shared/dashboard_list_item", fmea: fmea %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_fmea_header.html.erb
<div class="fmea-header">
  <div class="fmea-product-image">
    <i class="fas fa-file-upload"></i>
  </div>
  <div class="fmea-details">
    <div class="fmea-details-edit">
      <a data-toggle="modal" data-target="#editFmeaDetails" href="#"><i class="fas fa-pen"></i></a>
    </div>
    <h2><span class="light-blue"><%= fmea_type_icon(fmea) %></span> <%= fmea.title %></h2>
    <p><small><span class="light-blue"><i class="fas fa-th"></i></span>  <%= fmea.risk_matrix.name %></small></p>
    <p><%= simple_format(fmea.description) %></p>
  </div>
  <div class="fmea-stats">
    <div class="fmea-stat">
      <%= image_tag("function.svg", class: "pr-1") %>
      <span class="stat-number"><%= fmea.functions.count %></span>
    </div>
    <div class="fmea-stat">
      <%= image_tag("failure_mode.svg", class: "pr-1") %>
      <%= fmea.failure_modes.count %>
    </div>
    <div class="fmea-stat">
      <%= image_tag("cause.svg", class: "pr-1") %>
      <%= fmea.causes.count %>
    </div>
    <div class="fmea-stat">
      <%= image_tag("effect.svg", class: "pr-1") %>
      <%= fmea.effects.count %>
    </div>
  </div>
</div>
<!-- The Modal -->
<%= render "shared/edit_fmea_modal", fmea: fmea %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <!-- Thats the navbar when the user is signed in -->
  <div class="navbar bg-primary navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to fmeas_path, class: "navbar-brand nav-link" do %>
      <%= image_tag("logo/FMEAlite_logo.svg") %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav mr-auto">
        <% if user_signed_in? %>


          <div class="dropdown d-flex" style="width: 200px; justify-content: flex-end;">
            <div class="nav-item active my-auto mr-3 nav-link">
            </div>
            <span class="btn-clean dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%=  avatar(current_user) %>
            </span>
            
            <div class="dropdown-menu" >
              <a class="dropdown-item" href="/">Home</a>
              <!-- <a class="dropdown-item" href="#">Dashboard</a> -->
              <%= link_to("Dashboard", fmeas_path, class: "dropdown-item") %>
              <a class="dropdown-item" href="#">Account Settings</a>
              <%= link_to("Logout", destroy_user_session_path, method: :delete, class: "dropdown-item") %>
            </div>
          </div>

        <% else %>
          <div class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </div>
          <div class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-white" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Thats the navbar on the front page -->
<% else %>
  <div class="navbar bg-white navbar-expand-sm navbar-light navbar-lewagon">
    <div class="d-flex" style="justify-content: space-around; width: 100%;">
      <div class="d-flex" style="justify-content: space-around;">
        <%= link_to "/", class: "navbar-brand nav-link" do %>
            <%= image_tag("logo/FMEAlite_logo.svg") %>
        <% end %>
        <h4 class="text-body my-auto"><span style="font-weight:600">FMEA</span>.lite</h4>
      </div>

      <div class="d-flex" style="justify-content: flex-start; width: 300px;">


        <%= link_to(new_user_registration_path, class: "my-auto mr-4") do %>
            <button class="btn btn-success ">Get Started <svg class="bi bi-chevron-right" width="24" height="24" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6.646 3.646a.5.5 0 01.708 0l6 6a.5.5 0 010 .708l-6 6a.5.5 0 01-.708-.708L12.293 10 6.646 4.354a.5.5 0 010-.708z"/></svg>
            </button>
          <% end %>
        <%= link_to "Login", new_user_session_path, class: "text-white btn btn-primary my-auto px-4" %>
      </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  </div>

  </div>
<% end %>